name: Airbnb Monitor

on:
  schedule:
    # Run every 12 hours (at 6 AM and 6 PM UTC)
    - cron: '0 6,18 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager python-dotenv requests beautifulsoup4
    
    - name: Install Chrome
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Run Airbnb Monitor
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        AIRBNB_SEARCH_URL: ${{ secrets.AIRBNB_SEARCH_URL }}
        AIRBNB_SEARCH_URL_1: ${{ secrets.AIRBNB_SEARCH_URL_1 }}
        AIRBNB_SEARCH_URL_2: ${{ secrets.AIRBNB_SEARCH_URL_2 }}
        AIRBNB_SEARCH_URL_3: ${{ secrets.AIRBNB_SEARCH_URL_3 }}
      run: |
        python airbnb_monitor_github.py
    
    - name: Commit and push seen listings
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add seen_listings.json
        git diff --staged --quiet || git commit -m "Update seen listings - $(date)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
